### ISSUE TITLE
go-micro 新手，配置k8s 怎么跑起来？求教

### ISSUE THREAD

**Issue by day112** [yaoliu/k8s-micro#2]
go-micro 新手，配置k8s 怎么跑起来？求教
![image](https://user-images.githubusercontent.com/10526728/86878869-77b7ca00-c11c-11ea-8c89-8cab9a03306c.png)

**Comment by day112** [comment]
![image](https://user-images.githubusercontent.com/10526728/86878852-6cfd3500-c11c-11ea-9a41-2625e00c2053.png)

**Comment by yaoyaoio** [comment]
你这个需要在pod里运行才行 把main.go生成二进制 通过k8s运行在pod里
